### ISSUE TITLE
Only retain successful responses in cache

### ISSUE THREAD

**Issue by davin-english** [techniq/react-fetch-component#14]
Hi @techniq,

I saw you had a TODO on SimpleCache: `// TODO: only retain successful responses?`

Not sure how high this is on your priority list, but it would be a great help for my use-case (and I'm sure others). If there's a brief network error when making a fetch call, the URL gets set in the cache even though it errored. As such, subsequent calls are never made.

I'm currently working around this by removing the URL from the cache in the error callback, but it would be nice if the lib handled it for me (even if it's a prop on the Fetch component itself so users aren't forced into not caching unsuccessful calls). Having the lib handle it would remove a fair amount of boilerplate code where I'm doing the same workaround.

**Comment by techniq** [comment]
@davin-english I haven't ran into this so far to make it priority.  In sounds like you are using something similar to the [TODO](https://github.com/techniq/react-fetch-component/blob/master/src/SimpleCache.js#L9) within your code.  If so, and you think it's a good approach, I would be willing to merge a PR with the change.  If you could throw in a [test](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L1176) as well I would be most obliged.

**Comment by davin-english** [comment]
Yeah it's pretty close what what I'm doing (I'm actually using your react-odata lib), but my code more or less looks like this:
```
<OData baseUrl={props.connect.url} options={props.connect.options} cache={props.connect.cache} as={'json'}>
    {({ loading, error, data }) => {
        let someProp;

        if (data) {
            someProp = data.value;
        } else if (error) {
            someProp = 'An error occurred.';

            // here
            props.connect.cache.remove(props.connect.url);
        } else {
            someProp = 'Loading...';
        }

        return <SomeComponent propName={someProp}></SomeComponent>;
    }}
</OData>
```

**Comment by davin-english** [comment]
I'll look into adding your TODO to Fetch.js and adding a test for it if I have time.

In the meantime, I also noticed that on lines 132-134 in Fetch.js, you throw an error and return newState. Any chance you know of an alternative to not swallowing the error? The reason I ask is because I'm trying to test the `else if (error)` clause in my previous comment via Jest/jest-fetch-mock, but the test fails when the "throw" is encountered on line 132. If I remove it, and instead let it return newState, my test succeeds (and loads the correct error content which I can see in my snapshot).

**Comment by techniq** [comment]
Btw, I use [fetch-mock](http://www.wheresrhys.co.uk/fetch-mock/).  I had looked into using jest-fetch-mock, but ran into an [issue](https://github.com/jefflau/jest-fetch-mock/issues/9#issuecomment-277814838) when I tried using it a while back.  

I did just remember having an issue when I upgrade to fetch-mock 6.3 and have an test [skipped](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L1069).  If there is a better solution to error handling, I'm interested.  The things to be mindful of are:

- Not swallowing errors when the component's rendering/etc
- Handling a network error (CORS, etc)

**Comment by davin-english** [comment]
6.0.1 appears to be working great with the merge. I think this issue can be closed. I'll look into using an Error Boundary for the nextState issue. And depending on what I find, I'll let you know if I need to put up another PR for it.

**Comment by techniq** [comment]
Thanks for the update and sounds good.
