### ISSUE TITLE
`loading` initially starts as `null`?

### ISSUE THREAD

**Issue by mnpenner** [techniq/react-fetch-component#22]
Maybe I'm doing something wrong, but this seems weird to me. Here's my code:

```jsx
<Fetch url="/in-progress">
    {({loading, error, data}) => {
        console.log(loading,error,data);
        if(!data) {
            return <p>Loading...</p>
        }
    }}
</Fetch>
```

And the output:

![image](https://user-images.githubusercontent.com/1112998/45837647-9f7a3b80-bcc4-11e8-9d64-9d52094dcff8.png)

Loading is `null` on the first invocation. Why is that? I would think it'd *start* as `true`. this prevents me from doing `if(loading)` for my condition!

**Comment by techniq** [comment]
I did it this way intentionally so you know the request is in flight. This
is more noticeable with the manual prop.

**Comment by mnpenner** [comment]
Oh...yeah, okay, I get it. Fair enough.

**Comment by techniq** [comment]
@mnpenner Deployed as `7.0.0`.  `loading` will now be defaulted to `true` unless `manual` is set to `true`.

This will not save a `render` (still get 3 on the simple/typical [case](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L12-L46)) but this should simplify handling loading state and not require something like this:
```js
loading == null || loading ? (
  <Loading /> 
) : (
  <div>{data}</div>
)
```

**Comment by mnpenner** [comment]
@techniq Really? I just wrote up a [simple test](https://stackblitz.com/edit/react-bumsu1?file=index.js) and it only renders twice unless you call `setState` twice in `componentDidMount`.

I think it's because [this line](https://github.com/techniq/react-fetch-component/blob/bc98d54f2f9855f3a5c4c3884ccbd846511417c8/src/Fetch.js#L89) gets called even when mounting. Not sure if it's necessary or not, but three renders probably isn't a big deal anyway.

Thank you for releasing 7.0! That makes things easier.
