### ISSUE TITLE
Support refetching if `options.body` changes, even if url doesn't

### ISSUE THREAD

**Issue by ncknuna** [techniq/react-fetch-component#28]
In the version that I'm using, https://github.com/techniq/react-fetch-component/blob/ad8786215f9352b8c91524d753aa5ec7133383d4/src/Fetch.js#L58 specifies that we shouldn't refetch if the url hasn't changed. 

In my code I'm using this component with a POST call with a body, where the user can modify the page state to change the body, which I'd like to trigger a refetch, but since the URL is the same, it doesn't. I worked around this by adding a fragment to the end of the URL that takes a hash of the body, but it'd be nice if this just worked by default. At minimum, it would be good if this behavior was documented, since I had to spend a decent amount of time poking around before I figured it out.

**Comment by ncknuna** [comment]
Yea, I admit that this is a bit of an odd usecase; the API we're calling is doing an analytic query, so it's not actually modifying state, but it may require a lot of input params that are better suited to a body and the query isn't computationally cheap, so it's a POST (I also didn't design the API we're calling, so I don't have much control over the decision :P)

Yea, while `options.body` is my particular usecase, a more generic solution makes sense to me.

Yea, there are plenty of workarounds. We could use `manual`, or just keep doing the url fragment thing, so this isn't super urgent. It was mostly just not intuitive to change the body and have it not refetch and not know why without digging into source code.

**Comment by techniq** [comment]
@ncknuna I [added](https://github.com/techniq/react-fetch-component/commit/653420248230c8d065609eee01ffd1c1365e343e) support for this use case with a new `deps` (aka depenencies) prop.

I use this on new GraphQL component I'm working on where you always POST to the `/graphql` endpoint with a different body (query/variables).  So far it's working well (and plan to open source it once I've settled on the API.  Plan is to keep it lightweight (much more so than apollo-client, etc).  It's based on `react-fetch-component` similar to how my `react-odata` one was.

I need to update the docs to show `deps`, but take a look at the commit and tests.

**Comment by techniq** [comment]
@ncknuna Forgot to mention this is in `v8.0.0-9` prerelease.  Just waiting for Hooks to be released (maybe Feb 4th) but make it `8.0` stable.

**Comment by ncknuna** [comment]
Ah, cool, thanks :D
