### ISSUE TITLE
How to refetch data if error occured

### ISSUE THREAD

**Issue by TheAifam5** [techniq/react-fetch-component#29]
Hey!
I have a case where when the error while fetching occurs, I would give the user ability to try again using a button.
Would be nice to have the instance of current component, because I use the same functions for multiple components.

Regards,
TheAifam5.

**Comment by techniq** [comment]
@TheAifam5 This is supported using the `fetch` function passed to the child render function.

```jsx
<Fetch url="...">
  {({ loading, data, error, fetch }) => (
    <div>
      {loading && <Loading />}
      {data && <pre>{JSON.stringify(data, null, 2)}</pre>}
      {error && <button onClick={e => fetch()}>Retry</button>}
  )}
</Fetch>
```

`fetch()` can be used to retry, but is also available for manually initialed request `<Fetch url="..." manual>` which are useful for `POST`/`PUT` requests.

**Comment by TheAifam5** [comment]
@techniq Thank you. I wasn't sure about that `fetch` function. I was thinking that this function requires 2 parameters.

Thank you.
