### ISSUE TITLE
Uncaught (in promise) TypeError: failed to fetch

### ISSUE THREAD

**Issue by dlindahl** [techniq/react-fetch-component#3]
Fatal `fetch` errors are not caught and passed as props to the render callback.

To reproduce, make a `fetch` to any URL that does not support CORS (i.e. `https://example.org`). This will immediately fail to fetch the URL because the server does not respond with a `Access-Control-Allow-Origin` header.

Because the error occurs before the request is made, a response is never created. This causes the existing error handler to never run and thus allows errors to go uncaught.

This can be easily remedied by adding a `catch` clause to [the Promise](https://github.com/techniq/react-fetch-component/blob/a2ba19f6dc028f689d4e5e6c21c1835de5435f78/src/Fetch.js#L43-L59) to catch _any_ error and handle it appropriately through your error handler:

```js
.catch((error) => {
  const newState = {
    data: undefined,
    error,
    loading: false
  }
  this.setStateIfMounted(newState)
  return newState
});
```

**Comment by techniq** [comment]
@dlindahl thanks for the report.  I just published `1.0.2` that should fix this.
