### ISSUE TITLE
[Feature] Debounce requests

### ISSUE THREAD

**Issue by Andreyco** [techniq/react-fetch-component#6]
Add debounce feature, to throttle requests.

Eventually, if time allows me to, will provide PR.

**Comment by techniq** [comment]
I've considered adding this in the past, but think it's probably best to debounce when you call `setState` to issue the new request.  There is also a [Debounce](https://github.com/threepointone/react-debounce) component that might work for you.

I can still be talked into it (and have considered adding it in the past), but was trying to keep the component/api as simple as possible.  Definitely feel free to send a PR and we can discuss, as I'm not completely against the idea, I just want to make sure it's the best place to keep it.

Maybe just exposing a hook point to allow controlling when the requests are issued would be best.  Something like `onRequest` and you can return a promise/boolean to control whether to actually send the request, this way you can bring your own debounce/throttling implementation with you (lodash/etc, debounce on raising/falling edge, etc).

**Comment by techniq** [comment]
With the addition of the `fetchFunction` prop and example [test](https://github.com/techniq/react-fetch-component/blob/master/src/Fetch.test.js#L494) on how to use it for debouncing, I think that is the extent I'm going to add debouncing within `<Fetch>`.

If you look at the test, you'll see only a single network request after 4 are made in quick succession.  Doing it this way will still call multiple re-renders, but each of these will be given the same data as the last (and thus only) request.

I still think it's best to handle this outside of `Fetch`, such as using the `Debounce` component as this will remove the unnecessary rerenders.  You could also combine the 2 into a `DebouncedFetch` component and just pass all the props down to `Fetch` except for `period`.
